# Verwendete Build-Image
image = "netlify/build:focal"

# Build-Phasen
[build]
  # Verzeichnis für den veröffentlichten Inhalt
  publish = "dist"

  # Build-Schritte
  command = """
    apt-get update
    apt-get upgrade -y

    apt install openjdk-17-jdk openjdk-17-jre -y

    java -version
    
    gradle clean
    gradle bootJar

    cp build/libs/bastian-fischer.dev-API-0.0.1-SNAPSHOT.jar ../dist/

    cd ../dist/

    echo "web: java -jar bastian-fischer.dev-API-0.0.1-SNAPSHOT.jar" > Procfile

    echo "export JAVA_HOME=/opt/buildhome/jdk-17.0.1" > .profile

    java -jar dist/bastian-fischer.dev-API-0.0.1-SNAPSHOT.jar
  """

[build.environment]
  # Umgebungseinstellung für Java
  JAVA_HOME = "/opt/buildhome/jdk-17.0.1"
